### PR TITLE
Merge `Develop` into `Master, for Release 2.0.1?

### PR DESCRIPTION
**Pull request by aufdenkampe**
@horsburgh, this pull request includes your `Fix spelling of VariableExternalIdentifier` commit, which led me to find other similar misspellings of `Identifier` throughout the schema.

It seems like we might want to merge these changes in to Master, and perhaps issue a new ODM2 Release 2.0.1 once we have propagated those changes to the https://github.com/ODM2/ODM2PythonAPI and potentially beyond.

There are 15 commits presently in Master, mostly to docs but also to the `cvload.py` script.
See https://github.com/ODM2/ODM2/compare/v2.0.0...master

@horsburgh, @emiliom and @miguelcleon: What do you all think?

I think it would be good to have a new release, and I'm hoping that if we pointed everything properly to the 2.0.0 release, then it shouldn't really break anything. 

A new release, even this minor bug fix, would demonstrate that we are continuing to develop and support ODM2.

### CODE REVIEW

**Comment by aufdenkampe** [comment]
From @roelofversteeg, 9/17: “One comment I wanted to make is that the current DBWrench schema has the postgres oid for the UUID field, and this seems to be obsoleted, so maybe something to put on the list…”

**Comment by aufdenkampe** [comment]
@emiliom, can review the ODM2PythonAPI for any spelling errors for "Identifier"?

**Comment by aufdenkampe** [comment]
@emiliom and @horsburgh, Can we review this PR and issue a 2.0.1 release this week, in conjunction with the planned ODM2PythonAPI v0.7.2 release https://github.com/ODM2/ODM2PythonAPI/issues/165?

**Comment by horsburgh** [comment]
@aufdenkampe - It's the last week of classes and I've got a bunch of other stuff going. I may not get to any reviews this week. @emiliom - If you had time to review this it would be great. It should be pretty straightforward if it is just spelling fixes.

**Comment by emiliom** [comment]
I started reviewing this, but only via the DbWrench XML file here in github. I don't currently have DbWrench installed, and it'd be pretty hard to pick out what's changed via the DbWrench GUI.

On the XML file some of the changes were obvious: corrections to descriptions (not field names), and to a diagram name. But for others, I couldn't easily figure out what table was being changed.

I have no doubt that all these changes are valid and necessary (except for oversights), and I can see in the XML that the changes do correct mistakes. But what I'd like to see -- beyond actually reviewing the changes -- is whether these corrections impact anything that's currently handled by `odm2api`. Not that that's a reason not to merge this PR, but it'd be helpful to know.

@aufdenkampe did you list the specific changes somewhere else, maybe in an issue? 

Alternatively, maybe we should run the [code that exports database DDL's from the DbWrench XML](https://github.com/ODM2/ODM2/tree/master/src/build_schemas), then compare one of those DDL's (eg, PostgreSQL) to the 2.0.0 one. That'll be A LOT easier to handle than trying to work through the DbWrench XML.

Still, I don't want to tie an ODM 2.0.1 release to the odm2api release. They're unrelated. Though I can see the value of doing the two within a short time frame, to project a sense of ODM2 momentum.

Thoughts?

**Comment by aufdenkampe** [comment]
I'll be merging the develop branch and issuing a v2.0.1 release, to consolidate the various spelling errors identified by @horsburgh, @ptomasula, and me since 2016 and also to support the `UUID` datatype in PostgreSQL (given that the UniqueID/OID datatype has been deprecated, as described in #157).

This release will support work on a simplified and modernized version (Python 3.7 and latest SQLAlchemy) of the ODM2PythonAPI that we're developing in a forked branch at https://github.com/LimnoTech/ODM2PythonAPI/tree/python37update.

**Pull request merged**
